apiVersion : apps/v1
kind: Deployment
metadata:
  name: san-site-deploy
  labels:
    app  : san-site
    env  : prod
    owner: San144th
spec:
  replicas: 2
  selector:
    matchLabels:
      project: flaskapp
  template:
    metadata:
      labels:
        project: flaskapp
    spec:
      containers:
        - name : san-site-container
          image: san144th/flask_app:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: single-pod-service
  labels:
    env  : prod
    owner: San144th
spec:
  selector:
    project: flaskapp    # Selecting PODS with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8888  # Port on Load Balancer
      targetPort: 5000  # Port on POD
  type: LoadBalancer