#---------------------------------------------------------------------
# GitHub Action Workflow to Deploy Flask App to Kubernates cluster
#
# Version      Date        Info
# 1.0          2023        Initial Version
#
#---------------------------------------------------------------------

name: CI-CD-Pipeline-to-Kubernates

env:
  DEPLOY_PACKAGE_NAME        : "flask_app_${{ github.sha }}"
#  EB_APPLICATION_NAME       : "MyFlask"
#  EB_ENVIRONMENT_NAME       : "MyFlask-env"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id  : meta
        uses: docker/metadata-action@v4
        with:
          images: san144th/flask_app
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: user/app:latest
          labels: ${{ steps.meta.outputs.labels }}

#------------------------------------------------------------------------------------

#my_cd_part:
#  runs-on: ubuntu-latest
#  needs: [ci_part]

#  steps:
#  - name: executing remote ssh commands using password
#    uses: appleboy/ssh-action@v0.1.10
#    with:
#      host: ${{ secrets.KUBE_SSH_HOST }}
#      username: ${{ secrets.KUBE_SSH_USERNAME }}
#      key: ${{ secrets.KUBE_SSH_KEY }}
#      port: ${{ secrets.KUBE_SSH_PORT }}
#      script: |
#        whoami
#        ls -al
