name: Python tests
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой.
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          architecture: 'x64'
          
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
        
      - name: Install coverage
        run: pip install pytest-cov coveralls

      - name: Run tests
        run: coverage run hello_app/u_test.py
        
      - name: Tests report
        run: coverage report
        
